# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseFCMDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseFCMDemo
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'  
end
